name: Build and Deploy

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test FTP connection
        run: |
          if [ -z "${{ secrets.FTP_SERVER }}" ]; then
            echo "❌ FTP_SERVER is empty or not set"
          else
            echo "✅ FTP_SERVER is set (length: ${#FTP_SERVER})"
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: dist to master
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add -f dist/
          git commit -m 'update dist [skip ci]' || echo 'Нечего комитить'
          git push origin master
     
      - name: Prodaction
        if: github.ref == 'refs/heads/master'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /htdocs/www/
          clean: true

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          clean: true
