name: Build and Deploy

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: Config file
        run: | 
          echo "window.env = {" > dist/config.js
          echo "  SUPABASE_URL: '${{ secrets.SUPABASEURL }}'," >> dist/config.js
          echo "  SUPABASE_KEY: '${{ secrets.SUPABASEKEY }}'," >> dist/config.js
          echo "};" >> dist/config.js
      - name: Verify config
        run: cat dist/config.js

      - name: Prodaction
        if: github.ref == 'refs/heads/master'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /htdocs/www/
          clean: true

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          clean: true
